logging:
  level:
    root: info
    org.springframework: info
    com.redeyefrog: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  pattern:
    console: "%red(%d{yyyy-MM-dd HH:mm:ss}) %yellow([%thread]) %highlight(%-5level) %logger - %green(%msg%n)"

mock:
  file:
    upload:
      url: http://localhost:8081/mock/file